POST http://localhost:5117/api/tasks
Content-Type: application/json

{
  "title": "Verilənlər bazası əlaqəsini qurmaq",
  "description": "Entity Framework istifadə edərək PostgreSQL-ə qoşulmaq və miqrasiyaları etmək.",
  "status": "In Progress",
  "projectId": 3,
  "assignedToUserId": 1
}